intel-iot-devkit/iot-devkit-samples

digital-in/cpp/digital-in.cpp, digital-out/cpp/digital-out.cpp, onboard-blink/cpp/blink.cpp, pwm/cpp/pwm.cpp
Signed-off-by: Arun Ravindran <arun.ravindran@intel.com>
=> Joule: Fix issues with MRAA platform identification

azure-amqp/sample.json, azure-http/sample.json, azure-mqtt/sample.json
Fixing typo : HuB > hub
Correcting links.
[ISS-1068]
=> Fixing typo and correcting links

README.md, analog-in/cpp/analog-in.cpp, azure-amqp/sample.json, azure-http/sample.json, azure-mqtt/sample.json, bluemix-flame-detect/README.md, bluemix-flame-detect/cpp/BluemixFlameDetection.cpp, bluemix-quickstart/README.md, bluemix-quickstart/cpp/main.cpp, hello-world/c/main.c, hello-world/cpp/main.cpp
Bluemix: Define to avoid using hardware sensors, devices
Hello World: Avoid cout not displayed in console in small samples
Other minor changes
Signed-off-by: Shahab Layeghi <shahab.layeghi@intel.com>
=> Modifying samples

analog-in/cpp/README.md
Adding a soft link to the subfolder, so the README shows in the new project created by Intel System Studio.
=> added README link in analog-in

bluemix-flame-detect/README.md, bluemix-flame-detect/cpp/BluemixFDClientBase.cpp, bluemix-flame-detect/cpp/BluemixFlameDetection.cpp, bluemix-flame-detect/cpp/cpp.json, bluemix-flame-detect/sample.json, bluemix-quickstart/README.md, bluemix-quickstart/cpp/main.cpp, bluemix-quickstart/sample.json, interrupt/README.md, interrupt/cpp/interrupt.cpp, interrupt/sample.json, temperature-lcd/README.md, temperature-lcd/cpp/cpp.json, temperature-lcd/cpp/temperature-lcd.cpp
Please double check the pins/ports.
=> modify samples, set 2

aws-pub-sub/sample.json, azure-amqp/sample.json, azure-http/sample.json, azure-mqtt/sample.json, bluemix-flame-detect/sample.json, bluemix-quickstart/sample.json
- Add three optional attributes to a sample's sample.json file:
service_provider, service_provider_url, and
service_provider_description.
Signed-off-by: Jerroyd Moore <jerroyd.n.moore@intel.com>
=> Add Service Provider Info for Cloud Platforms

aws-pub-sub/sample.json, azure-amqp/sample.json, azure-http/sample.json, azure-mqtt/sample.json, bluemix-flame-detect/sample.json, bluemix-quickstart/sample.json
As per new branching strategy we do not need dev branches.
=> Iss2018 update1 dev into iss2018-update1

smart-pv-panels/cpp/smart-pv.cpp, sound-bar/cpp/sound-bar.cpp, tan-responsibly/cpp/tan-responsibly.cpp
1. mraa namespace missing.
2. typo in variable i2cPort.
=> Fix bugs in smart pv sample

google-pub/c/README.md, google-pub/c/c.json, google-pub/c/mqtt_ciotc.c, google-pub/sample.json
Pending : 
Right compile commands for the sample
=> Adding initial google sample

analog-in/maven/pom.xml, analog-in/maven/src/main/java/iotdk/example/AnalogIn.java, digital-in/maven/pom.xml, digital-in/maven/src/main/java/iotdk/example/DigitalIn.java, digital-out/maven/pom.xml, digital-out/maven/src/main/java/iotdk/example/DigitalOut.java, interrupt/maven/pom.xml, interrupt/maven/src/main/java/iotdk/example/Interrupt.java, onboard-blink/maven/pom.xml, onboard-blink/maven/src/main/java/iotdk/example/OnboardLedBlink.java, pwm/maven/pom.xml, pwm/maven/src/main/java/iotdk/example/PWM.java, temperature-lcd/maven/src/main/java/iotdk/example/DisplayTemperatureOnLCD.java
First change to java code sample
=> Java samples update preview

google-pub/c/mqtt_ciotc.c, google-pub/sample.json
This updates the project to run when built as a sample project in Intel System Studio. 
The README still needs to be updated.
=> Modify google-pub sample for build in Intel System Studio.

google-pub/c/README.md
Signed-off-by: Sisinty Sasmita Patra <sisinty.s.patra@intel.com>
=> ISS-634: Added/Updated Readme contents

up2-leds/README.md, up2-leds/cpp/cpp.json, up2-leds/cpp/up2-leds.cpp, up2-leds/maven/maven.json, up2-leds/maven/pom.xml, up2-leds/maven/src/main/java/iotdk/example/Up2Leds.java, up2-leds/sample.json
Signed-off-by: Mihai Tudor Panu <mihai.tudor.panu@intel.com>
=> up2-leds: adding new basic sample for UP2 built-in LEDs

onboard-blink/maven/src/main/java/iotdk/example/OnboardLedBlink.java
Signed-off-by: malikabh <abhishek.malik@intel.com>
=> Blink: Fixing the Java example

analog-in/maven/pom.xml, digital-in/maven/pom.xml, digital-out/maven/pom.xml, interrupt/maven/pom.xml, onboard-blink/maven/pom.xml, pwm/maven/pom.xml
Have kept base branch as update 1 but update2 will be the branch this goes in. Would not merge until : update 1 is merged into master. master is merged into update 2.
=> Updating to mraa 1.9.0

analog-in/maven/maven.json, automatic-curtain/maven/maven.json, digital-in/maven/maven.json, digital-out/maven/maven.json, hello-world/maven/maven.json, interrupt/maven/maven.json, onboard-blink/maven/maven.json, pwm/maven/maven.json, robot/maven/maven.json, smart-pv-panels/maven/maven.json, tan-responsibly/maven/maven.json, temperature-lcd/maven/maven.json, up2-leds/maven/maven.json
Signed-off-by: John K. Hines <john.k.hines@intel.com>
=> Updated maven sample metadata to set Docker support to false.

google-pub/sample.json
Just a small nitpick that I wanted to fix before we make videos on this.
=> Spell check on ID

azure-mqtt/cpp/cpp.json
Reverts intel-iot-devkit/iot-devkit-samples#89
=> Revert "Update cpp.json with -liothub_client_http_transport"

analog-in/maven/src/main/java/iotdk/example/AnalogIn.java, digital-in/maven/src/main/java/iotdk/example/DigitalIn.java, digital-out/maven/src/main/java/iotdk/example/DigitalOut.java, pwm/maven/src/main/java/iotdk/example/PWM.java, temperature-lcd/maven/src/main/java/iotdk/example/DisplayTemperatureOnLCD.java
also corrected gpio pin values the same as in cpp file
=> Platform name change to INTEL_UP2 in java samples

azure-amqp/cpp/cpp.json, azure-http/cpp/cpp.json, azure-mqtt/cpp/cpp.json
Added prov_auth_client, hsm_security_client, uhttp, and uuid libraries to JSON metadata files for Azure samples.
Signed-off-by: John K. Hines <john.k.hines@intel.com>
=> ISS-2150: Update Azure samples

analog-in/README.md, automatic-curtain/README.md, azure-amqp/README.md, azure-http/README.md, azure-mqtt/README.md, bluemix-flame-detect/README.md, bluemix-quickstart/README.md, digital-in/README.md, digital-out/README.md, interrupt/README.md, onboard-blink/c/README.md, onboard-blink/cpp/README.md, plant-health/README.md, pwm/README.md, smart-pv-panels/README.md, sound-bar/README.md, tan-responsibly/README.md, temperature-lcd/README.md, up2-leds/README.md
The changes implemented as written in description of the issue ISS-1799
=> Files README.md updated

analog-in/README.md, automatic-curtain/README.md, azure-amqp/README.md, azure-amqp/cpp/main.cpp, azure-http/README.md, azure-http/cpp/main.cpp, azure-mqtt/README.md, azure-mqtt/cpp/main.cpp, bluemix-flame-detect/README.md, bluemix-flame-detect/cpp/BluemixFlameDetection.cpp, bluemix-quickstart/README.md, bluemix-quickstart/cpp/main.cpp, digital-in/README.md, digital-out/README.md, google-pub/c/README.md, interrupt/README.md, onboard-blink/c/README.md, onboard-blink/cpp/README.md, plant-health/README.md, pwm/README.md, smart-pv-panels/README.md, sound-bar/README.md, tan-responsibly/README.md, tan-responsibly/cpp/tan-responsibly.cpp, temperature-lcd/README.md, temperature-lcd/cpp/temperature-lcd.cpp, up2-leds/README.md
Files README.md changed (asterisks, hyperlinks & board names updated)
=> Issdev 2043

up2-leds/c/c.json, up2-leds/c/up2-leds.c
LEDs sample (available only on Up Squared) was converted to C
=> up2-leds sample built in c added

aws-pub-sub/cpp/PubSub.cpp
Add comment to ignore false errors
=> Rewrite code to avoid false positive

analog-in/maven/pom.xml, digital-in/maven/pom.xml, digital-out/maven/pom.xml, interrupt/maven/pom.xml, onboard-blink/maven/pom.xml, pwm/maven/pom.xml, up2-leds/maven/pom.xml
The changes are made to run Java samples on IEI_TANK boards
=> MRAA dependencies are updated

analog-in/maven/pom.xml, digital-in/maven/pom.xml, digital-out/maven/pom.xml, interrupt/maven/pom.xml, onboard-blink/c/blink.c, onboard-blink/maven/pom.xml, pwm/maven/pom.xml, up2-leds/maven/pom.xml
=> ISSDEV-2045 (blink.c fixed for MRAA_IEI_TANK)

analog-in/sample.json, automatic-curtain/sample.json, aws-pub-sub/sample.json, azure-amqp/sample.json, azure-http/sample.json, azure-mqtt/sample.json, bluemix-flame-detect/sample.json, bluemix-quickstart/sample.json, digital-in/sample.json, digital-out/sample.json, google-pub/sample.json, hello-world/sample.json, interrupt/sample.json, onboard-blink/sample.json, plant-health/sample.json, pwm/sample.json, robot/sample.json, smart-pv-panels/sample.json, sound-bar/sample.json, tan-responsibly/sample.json, temperature-lcd/sample.json, up2-leds/sample.json
ISSDEV-3072: Update Dependencies with Tools. IoT Edition
`dependencies` JSON array updated (mostly with `iot-plugin` and `mraa` )
=> Update Dependencies with Tools. IoT Edition

analog-in/maven/pom.xml, automatic-curtain/maven/pom.xml, digital-in/maven/pom.xml, digital-out/maven/pom.xml, interrupt/maven/pom.xml, onboard-blink/maven/pom.xml, pwm/maven/pom.xml, temperature-lcd/maven/pom.xml, up2-leds/maven/pom.xml
Signed-off-by: agola <anjali.gola@intel.com>
=> ISS-2658 Updating samples to java 11

analog-in/README.md, automatic-curtain/README.md, azure-amqp/README.md, azure-http/README.md, azure-mqtt/README.md, bluemix-flame-detect/README.md, bluemix-quickstart/README.md, digital-in/README.md, digital-out/README.md, interrupt/README.md, onboard-blink/README.md, plant-health/README.md, pwm/README.md, smart-pv-panels/README.md, sound-bar/README.md, tan-responsibly/README.md, temperature-lcd/README.md, up2-leds/README.md
README.md files are updated to avoid confusion by names.
https://jira.devtools.intel.com/browse/ISSDEV-2437
=> ISSDEV-2437. Readme instructions say to kill "TCF agent" but in the IDE it’s labelled only “agent”	

hello-world/sample.json, onboard-blink/sample.json, up2-leds/sample.json
JIRA : https://jira.devtools.intel.com/browse/ISS-3015
Signed-off-by: agola <anjali.gola@intel.com>
=> Change category

onboard-blink/sample.json
Signed-off-by: agola <anjali.gola@intel.com>
=> Iss 3172 - Fix URL

analog-in/README.md, aws-pub-sub/cpp/README.md, azure-amqp/README.md, azure-http/README.md, azure-mqtt/README.md, bluemix-flame-detect/README.md, bluemix-quickstart/README.md, digital-in/README.md, digital-out/README.md, google-pub/c/README.md, interrupt/README.md, onboard-blink/README.md, pwm/README.md, up2-leds/README.md
README.md of each sample is updated with the link on the installation instruction for Ubuntu (on Up-series target platforms).
=> ISS-3219 Update readme for Ubuntu users

hello-world/cpp/main.cpp
It was noted in the DX studies that users tend to miss hello world run since it is so short. So adding a for loop to make it more noticeable.
For now, only making this change to c++. Once we confirm that this idea works in subsequent tests, we can make the change to other samples.
=> Make hello world more visual
